name: Libertrip
favicon: null
layout_spectrum: 0.27023
typography_spectrum: 0.70193682750687
title: Wellcome
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7fbee9'
    - '#555555'
    - '#f07c49'
    - '#171717'
  brandStrength: 0.5
  lightness: 0.5145777428988367
  saturation: 0.009833167539909482
  rhythmicContrast: 0.31625821883790195
purpose: []
